import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const out='/tmp/claude-0/-home-user-FusionStructure/6283d21d-eb25-5ade-923a-e4dcccb1d959/scratchpad/shots';
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
p.on('pageerror', e => errors.push(String(e)));
p.on('console', m => { if (m.type()==='error') errors.push(m.text()); });
await p.goto('http://127.0.0.1:5173', { waitUntil: 'networkidle' });
await p.click('.fs-action--primary'); await p.waitForTimeout(1800);
await p.click('.sc-home-nav--console [aria-label="Plantillas"]'); await p.waitForTimeout(1200);
await p.click('.sc-home-template-grid > button:nth-child(4)'); await p.waitForTimeout(3000);
await p.click('.console__analyze');
await p.waitForTimeout(220);
await p.screenshot({ path: `${out}/anim-mid.png` });
await p.waitForTimeout(2200);
await p.mouse.move(700, 400); await p.waitForTimeout(400);
await p.screenshot({ path: `${out}/anim-end.png` });
console.log('errors:', errors.slice(0,4));
await b.close();
